---
# tasks file for 2.nginx

    - name: install nginx
      apt:
        name: nginx
        update_cache: yes
        force: yes
        state: latest

    - name: Delete default nginx file
      file:
        path: /etc/nginx/sites-available/default
        state: absent

    - name: turn off server tokens
      lineinfile:
        path: /etc/nginx/nginx.conf
        regexp: "^	# server_tokens off;"
        line: '        server_tokens off;'
      notify: restart nginx
